version: '3.8'

services:

  app:
    image: ghcr.io/mikhail-angelov/bookadvisor:latest
    container_name: bookAdvisor
    networks:
      - proxy-net
    expose:
      - "3000"
    labels:
      monic.enabled: "true"
      monic.check: "http"
      monic.check_http_url: "https://advisor.bconf.com"
      monic.name: "advisor.bconf.com"
      redoproxy.enabled: "true"
      redoproxy.domain: "advisor.bconf.com"
      redoproxy.port: 3000
    volumes:
      - ./prod.db:/app/data/prod.db
      - ./crawl.db:/app/data/crawl.db
    env_file:
      - ./.env
    environment:
      - FLARESOLVERR_URL=http://flaresolverr:8191/v1
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    depends_on:
      - flaresolverr
    command: npm start

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    labels:
      monic.enabled: "true"
      monic.name: "flaresolverr"
    networks:
      - proxy-net
    ports:
      - "127.0.0.1:8191:8191"
    environment:
      - LOG_LEVEL=info
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

networks:
  proxy-net:
    external: true
